name: Deploy to WordPress.org
on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  deploy:
    name: Deploy new tag to SVN
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use a specific LTS version of Node.js

      - name: Install dependencies
        run: npm install

      - name: Build the plugin
        run: npm run build

      - name: Prepare plugin files for deployment
        run: |
          cp diana-greenconnect.php build/
          cp README.txt build/

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: diana-greenconnect
          BUILD_DIR: 'build/'
          ASSETS_DIR: 'assets/'
          VERSION: '1.0.2'

